apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argowordpress
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/cottoned/eddydogsrepo.git
    targetRevision: HEAD
    path: wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: argowordpress

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true